### ISSUE TITLE
Action failed on windows

### ISSUE THREAD

**Issue by tristancaron** [someara/kitchen-dokken#134]
## Configuration

- Windows 10 Home
- Docker 17.07.0-ce, build 8784753
- VirtualBox 5.1.26 r1 17224
- ChefDK 2.3.4
- chef-client 13.4.19
- berks 6.3.1
- kitchen 1.17.0
- inspec 1.36.1

## Detail

When I run `kitchen converge` inside of cookbook, I get an exception:
```
$ kitchen converge
-----> Starting Kitchen (v1.17.0)
-----> Creating <default-ubuntu-1604>...
      Creating kitchen sandbox at C:/Users/Tristan/.dokken/kitchen_sandbox/ba77048bc3-default-ubuntu-1604
      Creating verifier sandbox at C:/Users/Tristan/.dokken/verifier_sandbox/ba77048bc3-default-ubuntu-1604
      Building work image..
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
      Creating container ba77048bc3-default-ubuntu-1604
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [invalid mode: /opt/kitchen] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

The `kitchen.log` generated:
```
$ cat .kitchen/logs/kitchen.log
I, [2017-10-31T09:42:12.321711 #9660]  INFO -- Kitchen: -----> Starting Kitchen (v1.17.0)
I, [2017-10-31T09:42:16.895237 #9660]  INFO -- Kitchen: -----> Creating <default-ubuntu-1604>...
E, [2017-10-31T09:43:51.667700 #9660] ERROR -- Kitchen: ------Exception-------
E, [2017-10-31T09:43:51.678540 #9660] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-10-31T09:43:51.683440 #9660] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [invalid mode: /opt/kitchen
] on default-ubuntu-1604
E, [2017-10-31T09:43:51.684383 #9660] ERROR -- Kitchen: ----------------------
E, [2017-10-31T09:43:51.684383 #9660] ERROR -- Kitchen: ------Backtrace-------
E, [2017-10-31T09:43:51.684383 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:183:in `report_errors'
E, [2017-10-31T09:43:51.692277 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:174:in `run_action'
E, [2017-10-31T09:43:51.692277 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command/action.rb:36:in `block in call'
E, [2017-10-31T09:43:51.692277 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-10-31T09:43:51.693213 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command/action.rb:34:in `call'
E, [2017-10-31T09:43:51.693213 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/cli.rb:53:in `perform'
E, [2017-10-31T09:43:51.693213 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
E, [2017-10-31T09:43:51.694197 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2017-10-31T09:43:51.694197 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-10-31T09:43:51.694197 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2017-10-31T09:43:51.695175 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2017-10-31T09:43:51.695302 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2017-10-31T09:43:51.695302 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/bin/kitchen:13:in `block in <top (required)>'
E, [2017-10-31T09:43:51.696157 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-10-31T09:43:51.696401 #9660] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/bin/kitchen:13:in `<top (required)>'
E, [2017-10-31T09:43:51.696401 #9660] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:279:in `load'
E, [2017-10-31T09:43:51.697142 #9660] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:279:in `<main>'
E, [2017-10-31T09:43:51.697142 #9660] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-10-31T09:43:51.697142 #9660] ERROR -- Kitchen: -Composite Exception--
E, [2017-10-31T09:43:51.698190 #9660] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-10-31T09:43:51.698190 #9660] ERROR -- Kitchen: Message: Failed to complete #create action: [invalid mode: /opt/kitchen
] on default-ubuntu-1604
```

The result of `kitchen diagnose --all`: 
```
$ kitchen diagnose --all
---
timestamp: 2017-10-31 09:38:57 UTC
kitchen_version: 1.17.0
plugins:
  driver:
    Dokken:
      class: Kitchen::Driver::Dokken
      version:
      api_version:
  provisioner:
    Dokken:
      class: Kitchen::Provisioner::Dokken
      version: 1.17.0
      api_version: 2
  transport:
    Dokken:
      class: Kitchen::Transport::Dokken
      version: 1.17.0
      api_version: 2
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.19.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/Users/Tristan/IdeaProjects/bm-cookbook-griffin-api/.kitchen.yml
    raw_data:
      driver:
        name: dokken
        ports: 3000:8080
        chef_version: latest
      transport:
        name: dokken
      provisioner:
        name: dokken
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: ubuntu-16.04
        driver:
          image: ubuntu:16.04
          privileged: true
          pid_one_command: "/bin/systemd"
          intermediate_instructions:
          - RUN /usr/bin/apt-get update
      suites:
      - name: default
        run_list:
        - recipe[bm-mongodb]
        - recipe[local-mysql]
        - recipe[bm-griffin-api]
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: dokken
        ports: 3000:8080
        chef_version: latest
      transport:
        name: dokken
      provisioner:
        name: dokken
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: ubuntu-16.04
        driver:
          image: ubuntu:16.04
          privileged: true
          pid_one_command: "/bin/systemd"
          intermediate_instructions:
          - RUN /usr/bin/apt-get update
      suites:
      - name: default
        run_list:
        - recipe[bm-mongodb]
        - recipe[local-mysql]
        - recipe[bm-griffin-api]
instances:
  default-ubuntu-1604:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      last_error: Docker::Error::ServerError
    driver:
      api_retries: 20
      binds: []
      cap_add:
      cap_drop:
      chef_image: chef/chef
      chef_version: latest
      data_image: dokken/kitchen-cache:latest
      dns:
      dns_search:
      docker_host_url: tcp://192.168.99.100:2376
      docker_info:
        ID: KQA4:6YFI:L5CF:5LXB:74IY:RISS:XCOB:UE3U:2ERB:YYJB:SMFU:XK5Q
        Containers: 1
        ContainersRunning: 0
        ContainersPaused: 0
        ContainersStopped: 1
        Images: 5
        Driver: aufs
        DriverStatus:
        - - Root Dir
          - "/mnt/sda1/var/lib/docker/aufs"
        - - Backing Filesystem
          - extfs
        - - Dirs
          - '12'
        - - Dirperm1 Supported
          - 'true'
        SystemStatus:
        Plugins:
          Volume:
          - local
          Network:
          - bridge
          - host
          - macvlan
          - 'null'
          - overlay
          Authorization:
          Log:
          - awslogs
          - fluentd
          - gcplogs
          - gelf
          - journald
          - json-file
          - logentries
          - splunk
          - syslog
        MemoryLimit: true
        SwapLimit: true
        KernelMemory: true
        CpuCfsPeriod: true
        CpuCfsQuota: true
        CPUShares: true
        CPUSet: true
        IPv4Forwarding: true
        BridgeNfIptables: true
        BridgeNfIp6tables: true
        Debug: true
        NFd: 17
        OomKillDisable: true
        NGoroutines: 27
        SystemTime: '2017-10-31T09:38:41.467378823Z'
        LoggingDriver: json-file
        CgroupDriver: cgroupfs
        NEventsListener: 0
        KernelVersion: 4.4.93-boot2docker
        OperatingSystem: 'Boot2Docker 17.10.0-ce (TCL 7.2); HEAD : 34fe485 - Wed Oct
          18 17:16:34 UTC 2017'
        OSType: linux
        Architecture: x86_64
        IndexServerAddress: https://index.docker.io/v1/
        RegistryConfig:
          AllowNondistributableArtifactsCIDRs: []
          AllowNondistributableArtifactsHostnames: []
          InsecureRegistryCIDRs:
          - 127.0.0.0/8
          IndexConfigs:
            docker.io:
              Name: docker.io
              Mirrors: []
              Secure: true
              Official: true
          Mirrors: []
        NCPU: 1
        MemTotal: 2099486720
        GenericResources:
        DockerRootDir: "/mnt/sda1/var/lib/docker"
        HttpProxy: ''
        HttpsProxy: ''
        NoProxy: ''
        Name: default
        Labels:
        - provider=virtualbox
        ExperimentalBuild: false
        ServerVersion: 17.10.0-ce
        ClusterStore: ''
        ClusterAdvertise: ''
        Runtimes:
          runc:
            path: docker-runc
        DefaultRuntime: runc
        Swarm:
          NodeID: ''
          NodeAddr: ''
          LocalNodeState: inactive
          ControlAvailable: false
          Error: ''
          RemoteManagers:
        LiveRestoreEnabled: false
        Isolation: ''
        InitBinary: docker-init
        ContainerdCommit:
          ID: 06b9cb35161009dcb7123345749fef02f7cea8e0
          Expected: 06b9cb35161009dcb7123345749fef02f7cea8e0
        RuncCommit:
          ID: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
          Expected: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
        InitCommit:
          ID: 949e6fa
          Expected: 949e6fa
        SecurityOptions:
        - seccomp
        ExecutionDriver: "<not supported>"
      entrypoint:
      env:
      hostname: dokken
      image: ubuntu:16.04
      image_prefix:
      intermediate_instructions:
      - RUN /usr/bin/apt-get update
      kitchen_root: C:/Users/Tristan/IdeaProjects/bm-cookbook-griffin-api
      links:
      log_level: :info
      name: dokken
      network_mode: dokken
      pid_one_command: "/bin/systemd"
      ports: 3000:8080
      privileged: true
      read_timeout: 3600
      security_opt:
      test_base_path: C:/Users/Tristan/IdeaProjects/bm-cookbook-griffin-api/test/integration
      tmpfs: {}
      volumes:
      write_timeout: 3600
    provisioner:
      always_update_cookbooks: true
      attributes: {}
      chef_binary: "/opt/chef/embedded/bin/chef-client"
      chef_client_path: "/bin/chef-client"
      chef_log_level: warn
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_options: " -z"
      chef_output_format: doc
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      deprecations_as_errors: false
      docker_host_url: tcp://192.168.99.100:2376
      docker_info:
        ID: KQA4:6YFI:L5CF:5LXB:74IY:RISS:XCOB:UE3U:2ERB:YYJB:SMFU:XK5Q
        Containers: 1
        ContainersRunning: 0
        ContainersPaused: 0
        ContainersStopped: 1
        Images: 5
        Driver: aufs
        DriverStatus:
        - - Root Dir
          - "/mnt/sda1/var/lib/docker/aufs"
        - - Backing Filesystem
          - extfs
        - - Dirs
          - '12'
        - - Dirperm1 Supported
          - 'true'
        SystemStatus:
        Plugins:
          Volume:
          - local
          Network:
          - bridge
          - host
          - macvlan
          - 'null'
          - overlay
          Authorization:
          Log:
          - awslogs
          - fluentd
          - gcplogs
          - gelf
          - journald
          - json-file
          - logentries
          - splunk
          - syslog
        MemoryLimit: true
        SwapLimit: true
        KernelMemory: true
        CpuCfsPeriod: true
        CpuCfsQuota: true
        CPUShares: true
        CPUSet: true
        IPv4Forwarding: true
        BridgeNfIptables: true
        BridgeNfIp6tables: true
        Debug: true
        NFd: 17
        OomKillDisable: true
        NGoroutines: 27
        SystemTime: '2017-10-31T09:38:41.849782186Z'
        LoggingDriver: json-file
        CgroupDriver: cgroupfs
        NEventsListener: 0
        KernelVersion: 4.4.93-boot2docker
        OperatingSystem: 'Boot2Docker 17.10.0-ce (TCL 7.2); HEAD : 34fe485 - Wed Oct
          18 17:16:34 UTC 2017'
        OSType: linux
        Architecture: x86_64
        IndexServerAddress: https://index.docker.io/v1/
        RegistryConfig:
          AllowNondistributableArtifactsCIDRs: []
          AllowNondistributableArtifactsHostnames: []
          InsecureRegistryCIDRs:
          - 127.0.0.0/8
          IndexConfigs:
            docker.io:
              Name: docker.io
              Mirrors: []
              Secure: true
              Official: true
          Mirrors: []
        NCPU: 1
        MemTotal: 2099486720
        GenericResources:
        DockerRootDir: "/mnt/sda1/var/lib/docker"
        HttpProxy: ''
        HttpsProxy: ''
        NoProxy: ''
        Name: default
        Labels:
        - provider=virtualbox
        ExperimentalBuild: false
        ServerVersion: 17.10.0-ce
        ClusterStore: ''
        ClusterAdvertise: ''
        Runtimes:
          runc:
            path: docker-runc
        DefaultRuntime: runc
        Swarm:
          NodeID: ''
          NodeAddr: ''
          LocalNodeState: inactive
          ControlAvailable: false
          Error: ''
          RemoteManagers:
        LiveRestoreEnabled: false
        Isolation: ''
        InitBinary: docker-init
        ContainerdCommit:
          ID: 06b9cb35161009dcb7123345749fef02f7cea8e0
          Expected: 06b9cb35161009dcb7123345749fef02f7cea8e0
        RuncCommit:
          ID: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
          Expected: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
        InitCommit:
          ID: 949e6fa
          Expected: 949e6fa
        SecurityOptions:
        - seccomp
        ExecutionDriver: "<not supported>"
      encrypted_data_bag_secret_key_path:
      enforce_idempotency: false
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: C:/Users/Tristan/IdeaProjects/bm-cookbook-griffin-api
      log_file:
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: dokken
      named_run_list: {}
      nodes_path:
      policyfile:
      policyfile_path:
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path:
      root_path: "/opt/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[bm-mongodb]
      - recipe[local-mysql]
      - recipe[bm-griffin-api]
      sudo: true
      sudo_command: sudo -E
      test_base_path: C:/Users/Tristan/IdeaProjects/bm-cookbook-griffin-api/test/integration
      wait_for_retry: 30
    transport:
      docker_host_url: tcp://192.168.99.100:2376
      docker_info:
        ID: KQA4:6YFI:L5CF:5LXB:74IY:RISS:XCOB:UE3U:2ERB:YYJB:SMFU:XK5Q
        Containers: 1
        ContainersRunning: 0
        ContainersPaused: 0
        ContainersStopped: 1
        Images: 5
        Driver: aufs
        DriverStatus:
        - - Root Dir
          - "/mnt/sda1/var/lib/docker/aufs"
        - - Backing Filesystem
          - extfs
        - - Dirs
          - '12'
        - - Dirperm1 Supported
          - 'true'
        SystemStatus:
        Plugins:
          Volume:
          - local
          Network:
          - bridge
          - host
          - macvlan
          - 'null'
          - overlay
          Authorization:
          Log:
          - awslogs
          - fluentd
          - gcplogs
          - gelf
          - journald
          - json-file
          - logentries
          - splunk
          - syslog
        MemoryLimit: true
        SwapLimit: true
        KernelMemory: true
        CpuCfsPeriod: true
        CpuCfsQuota: true
        CPUShares: true
        CPUSet: true
        IPv4Forwarding: true
        BridgeNfIptables: true
        BridgeNfIp6tables: true
        Debug: true
        NFd: 17
        OomKillDisable: true
        NGoroutines: 27
        SystemTime: '2017-10-31T09:38:41.945103875Z'
        LoggingDriver: json-file
        CgroupDriver: cgroupfs
        NEventsListener: 0
        KernelVersion: 4.4.93-boot2docker
        OperatingSystem: 'Boot2Docker 17.10.0-ce (TCL 7.2); HEAD : 34fe485 - Wed Oct
          18 17:16:34 UTC 2017'
        OSType: linux
        Architecture: x86_64
        IndexServerAddress: https://index.docker.io/v1/
        RegistryConfig:
          AllowNondistributableArtifactsCIDRs: []
          AllowNondistributableArtifactsHostnames: []
          InsecureRegistryCIDRs:
          - 127.0.0.0/8
          IndexConfigs:
            docker.io:
              Name: docker.io
              Mirrors: []
              Secure: true
              Official: true
          Mirrors: []
        NCPU: 1
        MemTotal: 2099486720
        GenericResources:
        DockerRootDir: "/mnt/sda1/var/lib/docker"
        HttpProxy: ''
        HttpsProxy: ''
        NoProxy: ''
        Name: default
        Labels:
        - provider=virtualbox
        ExperimentalBuild: false
        ServerVersion: 17.10.0-ce
        ClusterStore: ''
        ClusterAdvertise: ''
        Runtimes:
          runc:
            path: docker-runc
        DefaultRuntime: runc
        Swarm:
          NodeID: ''
          NodeAddr: ''
          LocalNodeState: inactive
          ControlAvailable: false
          Error: ''
          RemoteManagers:
        LiveRestoreEnabled: false
        Isolation: ''
        InitBinary: docker-init
        ContainerdCommit:
          ID: 06b9cb35161009dcb7123345749fef02f7cea8e0
          Expected: 06b9cb35161009dcb7123345749fef02f7cea8e0
        RuncCommit:
          ID: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
          Expected: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
        InitCommit:
          ID: 949e6fa
          Expected: 949e6fa
        SecurityOptions:
        - seccomp
        ExecutionDriver: "<not supported>"
      host_ip_override: false
      kitchen_root: C:/Users/Tristan/IdeaProjects/bm-cookbook-griffin-api
      log_level: :info
      name: dokken
      read_timeout: 3600
      test_base_path: C:/Users/Tristan/IdeaProjects/bm-cookbook-griffin-api/test/integration
      write_timeout: 3600
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests: []
      kitchen_root: C:/Users/Tristan/IdeaProjects/bm-cookbook-griffin-api
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: C:/Users/Tristan/IdeaProjects/bm-cookbook-griffin-api/test/integration
```

**Comment by universam1** [comment]
very same problem here, any idea in meantime @tristancaron ?

**Comment by kranthi33** [comment]
Same issue any solution yet?

**Comment by sam1el** [comment]
Same issue here. 

Windows 10 Home
Docker 18.03.0-ce, 
VirtualBox 5.2.8 r121009 (Qt5.6.2)
Chefdk 3.4.18
chef-client 14.5.33
berks 7.0.6
kitchen 1.23.2
inspec 2.2.112

**Comment by Xorima** [comment]
I'm pretty sure this is related to the version of docker on windows and the versions of docker the ruby gem supports.

**Comment by Equalitism** [comment]
Is there any solution to this so far?
